### PR TITLE
Fix MECHA-230

### PR DESCRIPTION
**Pull request by theunkn0wn1**
Fixes MECHA-230 by replacing all instances of `'You need to be a registered and drilled Rat to execute this command!'`, `'Sorry, you need to be a registered and drilled Rat to use this command.'` and `'Sorry, but you need to be a registered and drilled Rat to use this command.'` with the variable `api.names.msg_not_idented`.

`api.names.msg_not_idented` is defined as string `"Sorry, but you need to be a registered and drilled Rat with an identified IRC nickname to use this command."`

The reason i redefined all the hardcoded strings to a variable is because it increases uniformity (we had 3 different messages stating the same thing!) and makes it more maintainable. If i went and search-replaced all the hardcoded string instances the next change would also have to be search-replace. Placing it as a single var means we just have to edit the string in one place rather than `n` cases

Update:
-------------
Refactored each `@require_{role}` decorator to have a default message, and changed all decorated instances to use the default, excluding those that specifically had no message.

### CODE REVIEW

**Review by Marenthyu — CHANGES_REQUESTED** [review]
If we are doing it this way already, i would set the message parameter as an optional parameter so the string doesn not have to be passed, only if it should deviate from the standard one.

**Comment by theunkn0wn1** [comment]
Well, it already has a default value for the optional parameter. According to the decorators top-level docstring:
```python
def require_rat(message=None):
    """Decorate a function to require the triggering user to be a FuelRats rat (as in, registered with the API and drilled).
    If they are not, `message` will be said if given.""
```
 the default is no message, `None` and, if the `message` is not None it prints it if the user fails the auth check. Granted I could find no instances of @require_rat with no given param, it made sense to have the default be None. However, I do see the value in having to evaluate the string only once, and not at every instance of the decorator. I will implement the change, test it, and push to this repo in a few hours time

**Comment by theunkn0wn1** [comment]
Should i also refactor the other require_{roll} decorators whilst im here? They all have essentially the same problem.

**Comment by Marenthyu** [comment]
Yes, please. Would be good if we're at it!
________________________________

**Comment by theunkn0wn1** [comment]
Refactoring complete. I actually see room for improvement here. it seems the different `require_{role}` decorators are all the same except for the
 ```python
if getPrivLevel(trigger) < privilage_level_int
```
line of each one. Honestly why is this not a single decorator with the privilege level as an argument?
We could define an enum class `Privilege` with fields `Privilege.Techrat`, `Privilege.Rat` etc
This would reduce redundancy and potential errors that may bring.

Edit: its worth noting that while i know some Python, im by no means a Pro just yet. Which is why im asking rather than simply doing it

**Comment by theunkn0wn1** [comment]
~~and some unrelated changes found their way out of the stash and into here. Don't merge yet.~~
Fixed. User did not understand what stash does

**Comment by theunkn0wn1** [comment]
@Marenthyu Can i get this PR reviewed sometime soon? before Firebeam tries to break it again?

**Review by Marenthyu — APPROVED** [review]

**Pull request merged**
