### PR TITLE
[BREAKING CHANGE]Renamed sopel-modules and the modules to abide by conventions.

### PR DESCRIPTION
**Pull request by theunkn0wn1**
The modules unfortunately were named with `-` characters in their name.
The unfortunate effect of this is that python will not recognize them, therefore they cannot be imported in other modules/scripts.

This is important if we want to do unit testing, or share resources across sopel modules.

Due to the fact the `sopel-modules` folder and the modules themselves have been renamed, the sopel.cfg file will need to be updated otherwise it will be unable to find the modules that make mecha squeak. (pun intended)

### CODE REVIEW

**Comment by Marenthyu** [comment]
Where exactly does this block anything?
From how i understand it, modules are **not supposed to be imported** and in any case, sopel has to be doing it somehow behind the scenes themselves.
Please elaborate more; but the name change shouldn't be a big problem otherwise.

But do be careful with importing modules, even if we go through with the change.

**Comment by theunkn0wn1** [comment]
Basicially if this PR stays open too long im concerned that further changes may cause conflicts.
Im not sure what would happen if something else was commited to develop, as ive had bad experiences with conflict resolution

Why its being imported, because Unit test files, from my understanding should not be in the same file as the module they test.
Therefore they must be able to import the tested module.
you cannot do
```python
import my-module
```
as `-` cannot be used in a module name (at least during import, it results in a syntax error) which is precicely **why** the files are being renamed.

**Comment by theunkn0wn1** [comment]
merge conflict... case in point

**Comment by theunkn0wn1** [comment]
Alright, i only intended to fix the merge conflict, not merge it yet without your final approval maren. 
Doesn't appear anything broke when this got merged, you will just have to update your `sopel.cfg` when you update mechasqueak-test.
Il leave the branch open for the moment should you decide to revert this

**Pull request merged**
