### PR TITLE
Drillsqueak auth and lang

### PR DESCRIPTION
**Pull request by Marenthyu**
Added all languages from reddit, added Auth Capability for API Calls

See commit b994353a5416b293c6c257dc29143435462a0233

### CODE REVIEW

**Comment by SuperManifolds** [comment]
@kenneaal Recommend checking this out on Rat Squeak, and updating the copy of the API it uses to latest master

**Comment by Marenthyu** [comment]
be aware that an apitoken needs to be **MANUALLY** generated for the api that is being used.

**Comment by kenneaal** [comment]
Suggest we test on drillsqueak first by enabling its API, running it against dev.api before we do ratsqueak. Can you update dev to latest and I can do the bot upgrade when I get home? Generate a key too, unsure of how.

**Comment by SuperManifolds** [comment]
Will do

**Comment by Marenthyu** [comment]
I'll make the token, will pm to you on irc once you're home.

**Comment by Marenthyu** [comment]
@xlexi updated the dev.api and my local version is working flawlessly in #MarenDev using Drillsqueak's auth token. Feel free to fiddle with it.

**Pull request merged**
