### PR TITLE
Feature/rat reddit

### PR DESCRIPTION
**Pull request by blackrabt**
This Sopel module checks reddit.com/r/fuelrats/new for new Ratsignal posts and notifies dispatch with their title and URL. If there are no new posts it will stay quiet. Can be summoned with ".reddit" command as well.
Config was updated to enable the module. All messages targeted at #rattest for now.

### CODE REVIEW

**Comment by Belserium** [comment]
What's the security on false/troll alarms over at reddit / across the module?

**Comment by blackrabt** [comment]
Nothing more than what exists in the IRC I suppose. The dispatcher and rats would have to look at the post and determine if it was legitimate the same way they do when talking to a client directly. There would be a counter post to give them instructions and if you didn't head back then it would be considered invalid. 
Aside from someone setting a trap for the assigned rats I think the real risk would be annoyance with junk posts. I considered a CMDR verification to make sure there was an actual pilot mentioned but I was unable to locate anything near a comprehensive list to search against. 
I am open to ideas if you have anything that might work.

**Comment by eddedmondson** [comment]
I think it's fine if it doesn't create cases and just notifies of new posts. If flooding is a concern just make it an 'x new posts since' alert if there's more than one.

**Comment by Belserium** [comment]
The spam vector is what came to my mind first. Granted that we may have some lag on IRC for kickbanning spammers out if janitorial presence is not present.

And as edmondson just said as I was typing, it is better that nothing is created to the bot's lists, just notified (maybe with a cooldown period).

**Comment by blackrabt** [comment]
Agreed. I don't want to try and replace the work the dispatchers do, I just want to get them good information in an easy/timely manner. 

The module could be changed to collect the total number of new distress calls since it last checked with some arrays if we want all the calls, or just a counter. 

The cooldown period is an interesting thought. It will stop after hitting one good post as it is written now, so someone spamming multiple distress calls will only bother the dispatcher with one per bot cycle. However we could add in something like a delay variable in this function. (this comment box really trashes the formatting v.v)

`@sopel.module.interval(delayTimer)
def repetition_text(bot):
    if "#rattest" in bot.channels:
        if botTalkToggle == True:
            #the system works, and will stay quiet if there is nothing to report. 
            bot.msg("#rattest", redditSubmissionTitle)`

if it runs through all 5 posts with no hits it sets it low, if it triggers on a distress call it sends it and sets the delay to a few minutes or however long people thing is good.

`def redditBotFunction(submission):
    ratsignalString='(Ratsignal)'   # use this for searching the post titles below
    lastPostTimestamp = datetime.datetime.fromtimestamp(int(submission.created_utc)).strftime('%Y-%m-%d %H:%M:%S')
    global currentPlaceInSubmissionList
    global redditSubmissionTitle
    global botTalkToggle
    global redditCheckTimer
        global delayTimer
    titleText = submission.selftext
    regExCheck = re.compile(ratsignalString,re.IGNORECASE|re.DOTALL)
    checkTitleForRatsignal = regExCheck.search(titleText)
    currentPlaceInSubmissionList += 1
    if checkTitleForRatsignal:
        word1=checkTitleForRatsignal.group(1)
        #set current place to 6 so it will not overwrite the valid distress call
        currentPlaceInSubmissionList = 6                    
        redditCheckTimer = (float(submission.created_utc))
        redditSubmissionTitle = submission.title
        botTalkToggle = True
                delayTimer = 300 #thats about 5 minutes
        #implement lastcall log
    elif (currentPlaceInSubmissionList == 5):
        redditSubmissionTitle = ("No new distress calls since " + lastPostTimestamp)
        botTalkToggle = False`
                delayTimer = 60

Another idea could be to try and add a second command trigger that will allow the IRC users to silence/unsilence the bot if there is a spamming issue going on. 
example:
`@sopel.module.commands('silence')
def set_silent(bot, trigger):
    masterTalkToggle = False`

With another to turn it back on, or shut it up for an hour or something.

**Comment by Belserium** [comment]
Yeah, this sounds good. My worries answered :)

**Comment by blackrabt** [comment]
Okay, in my local copy I added in a .silence toggle as well as a direct .silenceon and .silenceoff. If there is a Ratsignal received the next interval timer is increased to 5 minutes. Also added in a counter and message so if more than one Ratsignal is posted it will give a count of them. Right now the program still stops at the first good one, unless it cycles bottom to top, so next step would be to index all the posts and sort by date. Thoughts on all that? Any other concerns to address?

**Comment by blackrabt** [comment]
Closing to move rewritten module into drillsqueak.

**Pull request closed without merging**
