### PR TITLE
[facts]Now loading from a directory instead of a set file.

### PR DESCRIPTION
**Pull request by tyrope**
To help @Blackphidora with #40.

**this requires re-configuring the rat-facts module!** see the README changes for more information.

### CODE REVIEW

**Comment by duk3luk3** [comment]
> this requires re-configuring the rat-facts module

Go ahead and change the sopel.cfg as well then :-)

**Comment by tyrope** [comment]
_cough_ I totally knew we had a config example.

**Comment by trezy** [comment]
@duk3luk3 This PR looks good to me, mind if I merge it?

**Comment by tyrope** [comment]
#48 seems to be implemented way better.

**Pull request closed without merging**
